# Generated by Django 4.0 on 2022-11-23 01:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BBIT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('second_name', models.CharField(max_length=255)),
                ('ID_No', models.IntegerField()),
                ('group', models.CharField(max_length=255)),
                ('unit_name', models.CharField(max_length=255)),
                ('course_code', models.CharField(max_length=255)),
                ('academic_year', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='BTC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('second_name', models.CharField(max_length=255)),
                ('ID_No', models.IntegerField()),
                ('group', models.CharField(max_length=255)),
                ('unit_name', models.CharField(max_length=255)),
                ('course_code', models.CharField(max_length=255)),
                ('academic_year', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date created')),
            ],
        ),
        migrations.CreateModel(
            name='ICS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('second_name', models.CharField(max_length=255)),
                ('ID_No', models.IntegerField()),
                ('group', models.CharField(max_length=255)),
                ('unit_name', models.CharField(max_length=255)),
                ('course_code', models.CharField(max_length=255)),
                ('academic_year', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monday', models.CharField(max_length=255)),
                ('tuesday', models.CharField(max_length=255)),
                ('wednesday', models.CharField(max_length=255)),
                ('thursday', models.CharField(max_length=255)),
                ('friday', models.CharField(max_length=255)),
                ('time', models.TimeField()),
            ],
        ),
    ]
