# Generated by Django 4.0 on 2022-11-23 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecturer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unitregister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.CharField(max_length=2555)),
                ('email_address', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('second_name', models.CharField(max_length=255)),
                ('admission', models.CharField(max_length=255)),
                ('unit_name', models.CharField(max_length=255)),
                ('group', models.CharField(max_length=255)),
                ('lec_first_name', models.CharField(max_length=255)),
                ('lec_second_name', models.CharField(max_length=255)),
            ],
        ),
    ]
